name: Erlang CI

on:
  push:
    branches:
    - develop-3.4
  pull_request:
    branches:
    - develop-3.4

jobs:

  build:

    name: Test on ${{ matrix.os }} with OTP ${{ matrix.otp }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        otp: [24, 26]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Install Erlang/OTP
      uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp }}
    - name: Compile
      run: ./rebar3 compile
    - name: Run tests
      run: ./rebar3 do xref, dialyzer, eunit
